- name: Change Shell to zsh
  shell: chsh -s /bin/zsh

- name: Create ~/bin/
  file:
    path: ~/bin
    state: directory
    mode: 0755

- name: Git-Foresta Download
  get_url:
    url: https://github.com/takaaki-kasai/git-foresta/raw/master/git-foresta
    dest: ~/bin/git-foresta

- name: Add Execute for git-foresta
  shell: chmod +x ~/bin/git-foresta

- name: Delete Karabiner-Elements Default Config
  file:
    path: ~/.config/karabiner
    state: absent

- name: Create Symbolic Link for Karabiner-Elements
  file:
    src: ~/GoogleDrive/dotfiles/karabiner
    dest: ~/.config/karabiner
    state: link

- name: Create Symbolic Link for .gitconfig
  file:
    src: ~/GoogleDrive/dotfiles/.gitconfig
    dest: ~/.gitconfig
    state: link

- name: Create Symbolic Link for .zshrcf
  file:
    src: ~/GoogleDrive/dotfiles/.zshrc
    dest: ~/.zshrc
    state: link

- name: Create Symbolic Link for .zsh.d
  file:
    src: ~/GoogleDrive/dotfiles/zsh.d
    dest: ~/.zsh.d
    state: link

- name: Create Symbolic Link for .tmux.conf
  file:
    src: ~/GoogleDrive/dotfiles/tmux.conf
    dest: ~/.tmux.conf
    state: link

