- block:

  - name: Download ricty
    get_url:
      url: http://www.rs.tus.ac.jp/yyusa/ricty_diminished/ricty_diminished-4.1.1.tar.gz
      dest: ~/Downloads/ricty_diminished-4.1.1.tar.gz

  - name: Unzip ricty
    raw: tar zxvf ~/Downloads/ricty_diminished-4.1.1.tar.gz -C ~/Library/Fonts/

  - name: Download Source Han Code JP
    get_url:
      url: https://github.com/adobe-fonts/source-han-code-jp/archive/2.000R.tar.gz
      dest: ~/Downloads/2.000R.tar.gz

  - name: Unzip Source Han Code JP
    raw: tar zxvf ~/Downloads/2.000R.tar.gz  -C ~/Library/Fonts/

  - name: mv *.otf to  ~/Library/Fonts/
    copy:
      src: "{{ item }}"
      dest: "~/Library/Fonts"
    with_fileglob:
      - ~/Library/Fonts/source-han-code-jp-2.000R/OTF/*.otf

  - name: fc-cache
    raw: fc-cache -vf