homebrew_cask_packages:
  - { name: docker }
  - { name: spectacle }
  - { name: alfred }
  - { name: slack }
  - { name: google-chrome }
  - { name: google-drive }
  - { name: karabiner-elements }
  - { name: wezterm }
  - { name: notion }
  - { name: notion-calendar }
  - { name: line }
  - { name: 1password }
