- block:

  - name: zsh Config Load
    shell: ln -s ~/Dropbox/dotfiles/zshrc ~/.zshrc
    ignore_errors: yes

  - name: Change Shell to zsh
    shell: chsh -s /bin/zsh

  - name: Create ~/bin/
    file:
      path: ~/bin
      state: directory
      mode: 0755

  - name: Git-Foresta Download
    get_url:
      url: https://github.com/takaaki-kasai/git-foresta/raw/master/git-foresta
      dest: ~/bin/git-foresta

  - name: Add Execute for git-foresta
    shell: chmod +x ~/bin/git-foresta

  - name: zsh Load
    shell: /bin/zsh -lc "source ~/.zshrc"
