- block:

  - name: Copy home directory Files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - "{{ HOMEDIR_TARGETS }}"

  - name: zsh Config Load
    shell: ln -s OneDrive/dotfiles/zshrc ~/.zshrc

  - name: Sublime Text3 Config Load 1
    shell: ln -s ~/OneDrive/Sublime\ Text\ 3/Installed\ Packages ~/Library/Application\ Support/Sublime\ Text\ 3/
    
  - name: Sublime Text3 Config Load 2
    shell: ln -s ~/OneDrive/Sublime\ Text\ 3/Packages ~/Library/Application\ Support/Sublime\ Text\ 3/

  - name: Change Shell to zsh
    shell: chsh -s /bin/zsh

  - name: Create ~/bin/
    file:
      path: ~/bin
      state: directory
      mode: 0755
    
  - name: Git-Foresta Download
    get_url:
      url: https://github.com/takaaki-kasai/git-foresta/raw/master/git-foresta
      dest: ~/bin/git-foresta
    
  - name: Add Execute for git-foresta
    shell: chmod +x ~/bin/git-foresta