- block:
    - name: Install cask packages
      ignore_errors: true
      homebrew_cask: name={{ item.name }}
        state={{ item.state | default('present') }}
      with_items:
        - "{{ homebrew_cask_packages }}"
