- block:
    - name: download Myrica
      get_url:
        url: https://github.com/tomokuni/Myrica/raw/master/product/MyricaM.zip
        dest: ~/Downloads/MyricaM.zip

    - name: unzip Myrica
      raw: tar zxvf ~/Downloads/MyricaM.zip -C ~/Library/Fonts/
